name: Build Anomaly Mod
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Güncellendi (Uyarıyı giderir)
      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Güncellendi (Node.js uyarısını giderir)
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # Güncellendi (Hatayı çözer)
        with:
          name: Anomaly-0-Mimic-Ultimate
          path: build/libs/*.jar
          
